### ISSUE TITLE
Mon_smoky_bear isn't mainline anymore

### ISSUE THREAD

**Issue by Malkeus** [chaosvolt/Dorf-Life-CDDA#1]
They've done gone and put mon_smoky_bear into crazy cataclysm and broke yer mod, pardner. I put a fix out there, but it's just a deletion, no art to it.
https://discourse.cataclysmdda.org/t/a-wandering-updater-appears-works-with-b8166-added-warhammer-40k/17267/87

By the way, nice to see you around ;)

**Comment by chaosvolt** [comment]
Doh. Will fix in a second, smokies aren't really needed for it so I can easily just drop them.
