### ISSUE TITLE
init_vehicles: 'Wagon' part 'wheel_wood'(12) can't be installed to 0,2

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/Dorf-Life-CDDA#10]
DEBUG    : init_vehicles: 'Wagon' part 'wheel_wood'(12) can't be installed to 0,2

 FUNCTION : static void vehicle_prototype::finalize()
 FILE     : src/veh_type.cpp
 LINE     : 1447
 VERSION  : 2ed6865

**Comment by chaosvolt** [comment]
Hecc, will update this when I get back home later today.

**Comment by chaosvolt** [comment]
There we go, sorry for the delay.
