### ISSUE TITLE
Glitch when starting a new game 

### ISSUE THREAD

**Issue by Torres84f** [chaosvolt/Dorf-Life-CDDA#4]
I got this message 
` DEBUG    : Error: data/mods//Dorf_Life/gates.json: line 3:20: must specify either id or abstract

[
  {
    "type": "gate",
                   ^
    "id": "t_breach_lever",
    "door": "t_breach_stone_fake",
    "floor": "t_breach_stone_fake_lowered",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781
`

I'm on 
Platform     : Windows_x64
Graphics     : Tiles
Build number : #10479
Build version: 0.E-2
Major version: 0.E

Can't start the game with the mod so I'll disable and check out here from time to time see if I can provide more info

**Comment by chaosvolt** [comment]
Looks like an issue caused by using 0.E Stable with the master branch of the mod, which is presently compatible with latest experimental builds. I didn't have the chance to set aside a 0.E release for this mod yet due to juggling various other things. If you want I can go ahead and do so now.

**Comment by chaosvolt** [comment]
There we go, this release should work for it: https://github.com/chaosvolt/Dorf-Life-CDDA/releases/tag/0.E

Do tell if anything else comes up, though.
