### ISSUE TITLE
Error when starting new game with Dorf Life in 0-G

### ISSUE THREAD

**Issue by BoxTrot** [chaosvolt/Dorf-Life-CDDA#6]
When starting a new game in 0-G with a world containing Dark Days Ahead and Dorf Life, CDDA returns an error immediately upon loading Dorf Life (pre-chargen). The error log is pasted below:

```
 DEBUG    : Error: data/mods//Dorf_Life/construction.json: line 4:37: requested non-existing member "description"

[
  {
    "type": "construction",
    "id": "constr_dorf_removegrass",
                                    ^
    "group": "remove_grass",
    "category": "OTHER",
    "required_skills": [ [ "survival", 0 ] ],


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 887

```

Steps to reproduce:

1. Install Dorf Life in a normal install of CDDA 0-G.
2. Create a new world with just the mods Dark Days Ahead and Dorf Life selected.
3. Create a new game using a random character with the new world.
4. The game will generate the above error when loading Dorf Life. After pressing space, the game will return to the main menu instead of confirming the new character.

Solution:

- Add the following line after "id" in construction.json:
`"description": "test",`

Result:

- The error above relating to a missing description is now gone, but another error log appears:

```
 DEBUG    : Error: data/mods//Dorf_Life/gates.json: line 3:20: must specify either id or abstract

[
  {
    "type": "gate",
                   ^
    "id": "t_breach_lever",
    "door": "t_breach_stone_fake",
    "floor": "t_breach_stone_fake_lowered",


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

```

**Comment by chaosvolt** [comment]
0-G is an april fools day release that's just a release of 0.E stable, I'm not not even going to bother setting aside a release for that shit. Wait for the actual 0.F release or use the right version with recent 0.E experiemental builds.

**Comment by BoxTrot** [comment]
Sorry, I had no idea it wasn't a real release - I started playing CDDA around April Fool's Day and just thought the devs were crazy when I read through the release notes.

**Comment by chaosvolt** [comment]
It doesn't help that, if I recall, 0.D Stable actually did release on an april fools day.
