### ISSUE TITLE
Nest placement bounds checking

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/Dorf-Life-CDDA#8]
DEBUG    : nest breach_chunk_1 within mapgen breach_finale_3 can place something at x = 26, which is in a different OMT from the smallest nest origin (5, 0), and could lead to an out of bounds placement

 FUNCTION : virtual void jmapgen_nested::check(const string&, const mapgen_parameters&, const jmapgen_int&, const jmapgen_int&) const
 FILE     : src/mapgen.cpp
 LINE     : 3301
 VERSION  : 04143c6

**Comment by chaosvolt** [comment]
Thanks for spotting that. https://github.com/chaosvolt/Dorf-Life-CDDA/commit/e665f037b89f5e8b0dbb1dfeeb263da62f6ab563 should fix it, do tell if you spot anything else that comes up.
