### ISSUE TITLE
Unknown item ID & Missing Definition

### ISSUE THREAD

**Issue by CptForesight** [chaosvolt/Dorf-Life-CDDA#9]
The following two errors occur on character creation with a world that has this mod loaded.

` DEBUG    : item id small_homemade_grenade is unknown (in entry within cavern_cabin)

 FUNCTION : virtual void Single_item_creator::check_consistency() const
 FILE     : src/item_group.cpp
 LINE     : 267
 VERSION  : 0.F-3
`
` DEBUG    : Missing item definition: small_homemade_grenade

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1555
 VERSION  : 0.F-3
`

**Comment by chaosvolt** [comment]
Oh right shit, I'd forgot to make a 0.F stable release for this mod. Though by now they're probably halfway to making 0.G, hmm. :/

**Comment by CptForesight** [comment]
Absolutely focus your energies on 0.G if you feel thats a better use and then hopefully make it G compatible, so I can extend my underground living!

**Comment by chaosvolt** [comment]
I'll have to work on this soon yeah. Still a fair bit unfinished with this mod in the first place @.@

**Comment by CptForesight** [comment]
I appreciate your speedy response and apologies on my other issues raised, I am still getting used to GitHub.

The concept is a brilliant idea to expand an under utilized part of the game, with its usefulness as travel and even shelter, your expansion of it is much appreciated for us subway people.

**Comment by chaosvolt** [comment]
No worries. In the meantime, current master branch of the mod should be working with 0.F experimental and BN.

**Comment by chaosvolt** [comment]
And there we go, this should fix it: https://github.com/chaosvolt/Dorf-Life-CDDA/releases/tag/0.F
